version: "3.8"
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  prisma:
    image: backend_boilerplate
    restart: always
    depends_on:
      - "postgres"
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/mydb?schema=public
  nginx:
    image: nginx
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
volumes:
  postgres:
